#
# Load precomputed domain data as generated by cdd-compute-domains.
#
# Note that as of the initial commit of this code the ordering in the
# generated data has the first two columns reversed from their original
# order in the rpsblast output. This was a misguided effort to make
# the file format match the column order in the native table. It doesn't
# work anyway as we need to explicitly specify the column order.
#
# This first version of the loader assumes no domain relationship information
# is present; this will make the bulk loads much more efficient as the
# database can just load and index the data. For adding to the 
# data we probably need to do like Bruce's other loaders and ensure
# we don't insert duplicate data.
#

use strict;
use Bio::KBase::CDMI::CDMIClient;
use Data::Dumper;

my $cdmi = Bio::KBase::CDMI::CDMI->new_for_script();

my $dbh = $cdmi->{_dbh};

@ARGV == 1 or die "Usage: $0 [standard CDMI database flags] input-file-directory\n";

my $input_dir = shift;

opendir(D, $input_dir) or die "Cannot open input directory $input_dir: $!";

print "Load from $input_dir\n";


